import { createHash } from 'node:crypto';

import { assertPublicData } from './privacy.ts';
import {
  FOUNDATION_CONTRACT_IDS,
  LiveContractValidationError,
  REQUIRED_LIVE_VARIANTS,
  SMOKE_VARIANT_IDS,
  requiredSuitesForVariant,
  validateLiveCatalogShape,
  type EntryPoint,
  type LiveCatalog,
  type LiveContract,
  type LiveManifest,
  type Suite,
} from './schema.ts';

export function compileLiveCatalog(input: unknown): LiveManifest {
  assertPublicData(input);
  const catalog = validateLiveCatalogShape(input);
  const contractIds = catalog.contracts.map((contract) => contract.id);
  if (new Set(contractIds).size !== contractIds.length) {
    throw new LiveContractValidationError('DUPLICATE_ID', '$.contracts');
  }
  validateInventory(catalog);
  const contracts = normalizeContracts(catalog.contracts);
  const allVariantIds = contracts.flatMap((contract) => contract.variants.map((variant) => variant.id));
  if (new Set(allVariantIds).size !== allVariantIds.length) {
    throw new LiveContractValidationError('DUPLICATE_ID', '$.contracts.variants');
  }
  const candidateIds = contracts.flatMap((contract) =>
    contract.variants.flatMap((variant) => variant.regressions.map((regression) => regression.candidateId))
  );
  if (new Set(candidateIds).size !== candidateIds.length) {
    throw new LiveContractValidationError('DUPLICATE_ID', '$.contracts.regressions');
  }

  const requiredVariants: Record<Suite, string[]> = {
    case: [...allVariantIds].sort(),
    smoke: [...SMOKE_VARIANT_IDS].sort(),
    deep: [...allVariantIds].sort(),
  };
  const payload = {
    schemaVersion: 'chickpea-live-manifest/v1' as const,
    release: catalog.release,
    pendingContractIds: [...catalog.pendingContractIds].sort(),
    requiredVariants,
    contracts,
  };
  const digest = `sha256:${createHash('sha256').update(canonicalJson(payload)).digest('hex')}`;
  return deepFreeze({ ...payload, digest });
}

export function manifestJson(manifest: LiveManifest): string {
  return `${canonicalJson(manifest)}\n`;
}

export function renderFeatureMap(manifest: LiveManifest): string {
  const entryPoints = new Map<EntryPoint, string[]>();
  for (const contract of manifest.contracts) {
    for (const entryPoint of contract.entryPoints) {
      const contracts = entryPoints.get(entryPoint) ?? [];
      contracts.push(contract.id);
      entryPoints.set(entryPoint, contracts);
    }
  }
  const lines = [
    '# Live contract feature map',
    '',
    '<!-- Generated by qa/live/compiler.ts. Do not edit by hand. -->',
    '',
    `Manifest: \`${manifest.digest}\``,
    '',
    '## Contracts',
    '',
    '| Contract | Title | Feature | Required variants |',
    '| --- | --- | --- | --- |',
    ...manifest.contracts.map((contract) =>
      `| ${contract.id} | ${contract.title} | \`${contract.feature}\` | ${contract.variants.map((variant) => `\`${variant.id}\``).join(', ')} |`
    ),
    '',
    '## Entry points',
    '',
    '| Entry point | Contracts |',
    '| --- | --- |',
    ...[...entryPoints.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([entryPoint, contracts]) =>
      `| \`${entryPoint}\` | ${[...contracts].sort().join(', ')} |`
    ),
    '',
  ];
  return lines.join('\n');
}

export function assertFeatureMapFresh(current: string, manifest: LiveManifest): void {
  if (current !== renderFeatureMap(manifest)) {
    throw new LiveContractValidationError('FEATURE_MAP_STALE', '$.generated.featureMap');
  }
}

function validateInventory(catalog: LiveCatalog): void {
  const allContractIds = Object.keys(REQUIRED_LIVE_VARIANTS).sort();
  const expectedContractIds = catalog.release === 'v1.0'
    ? [...FOUNDATION_CONTRACT_IDS].sort()
    : allContractIds;
  const expectedPending = catalog.release === 'v1.0'
    ? allContractIds.filter((id) => !expectedContractIds.includes(id as typeof FOUNDATION_CONTRACT_IDS[number]))
    : [];
  const actualContractIds = catalog.contracts.map((contract) => contract.id).sort();
  if (!same(actualContractIds, expectedContractIds) || !same([...catalog.pendingContractIds].sort(), expectedPending)) {
    throw new LiveContractValidationError('INVENTORY_MISMATCH', '$.contracts');
  }
  for (const contract of catalog.contracts) {
    const expectedVariants = REQUIRED_LIVE_VARIANTS[contract.id as keyof typeof REQUIRED_LIVE_VARIANTS];
    if (expectedVariants === undefined || !same(
      contract.variants.map((variant) => variant.id).sort(),
      [...expectedVariants].sort(),
    )) {
      throw new LiveContractValidationError('INVENTORY_MISMATCH', `$.contracts.${contract.id}.variants`);
    }
    for (const variant of contract.variants) {
      if (!same([...variant.suites].sort(), requiredSuitesForVariant(variant.id).sort())) {
        throw new LiveContractValidationError('INVENTORY_MISMATCH', `$.contracts.${contract.id}.${variant.id}.suites`);
      }
    }
  }
}

function normalizeContracts(contracts: LiveContract[]): LiveContract[] {
  return [...contracts]
    .map((contract) => ({
      ...contract,
      entryPoints: [...contract.entryPoints].sort(),
      variants: [...contract.variants]
        .map((variant) => ({
          ...variant,
          suites: [...variant.suites].sort(),
          fixtures: [...variant.fixtures].sort((left, right) => left.slot.localeCompare(right.slot)),
          observers: [...variant.observers].sort(),
          expected: [...variant.expected].sort(assertionOrder),
          forbidden: [...variant.forbidden].sort(assertionOrder),
          regressions: [...variant.regressions].sort((left, right) => left.candidateId.localeCompare(right.candidateId)),
          evidence: [...variant.evidence].sort(),
        }))
        .sort((left, right) => left.id.localeCompare(right.id)),
    }))
    .sort((left, right) => left.id.localeCompare(right.id));
}

function assertionOrder(left: { token: string; observerId: string }, right: { token: string; observerId: string }): number {
  return `${left.token}:${left.observerId}`.localeCompare(`${right.token}:${right.observerId}`);
}

function same(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((value, index) => value === right[index]);
}

function canonicalJson(value: unknown): string {
  return JSON.stringify(canonicalize(value));
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value as Record<string, unknown>)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, child]) => [key, canonicalize(child)]));
}

function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object') {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  }
  return value;
}
