import { defineTool, usePersistentState, useResponseStart, type JsonValue } from '@flue/runtime';
import * as v from 'valibot';

import type {
  ImageCallFailureReason,
  ImageCallResult,
  ImageCallUsage,
  ImageFormatPolicy,
  ImageInput,
  ImageOutputFormat,
  OpenAiImagesClient,
} from '../images/openai-images-client.ts';
import { assertArtifactDeliveryAllowed } from '../memory/tool-policy.ts';
import {
  DEFAULT_THREAD_IMAGE_FILE_LIMIT_BYTES,
  THREAD_IMAGE_HANDLE_PREFIX,
  type ThreadImageInventory,
  type ThreadImageReader,
  type ThreadImageUnavailableDetail,
} from '../slack/thread-images.ts';
import {
  artifactFilename,
  MAX_ARTIFACT_BYTES,
  MAX_ARTIFACT_FILENAME_CHARS,
  type SlackArtifactStageInput,
  type SlackArtifactStageOutcome,
} from './artifact-tool.ts';

export const GENERATE_IMAGE_TOOL_NAME = 'generate_image';
/** The Agent composes the prompt; the cap keeps one tool call bounded. */
export const MAX_IMAGE_PROMPT_CHARS = 4_000;
/** Thread image handles one call may reference. */
export const MAX_IMAGE_TOOL_INPUTS = 4;
/**
 * Variations one call may ask for. The response still gets one image call;
 * this bounds how many files that call can attach and how long it can hold
 * the lane, since the provider renders variations in one round trip.
 */
export const MAX_IMAGE_TOOL_OUTPUTS = 4;
/**
 * Stall guard, not a budget cap: above the provider's documented
 * two-minute worst case, so only a network-level stall releases the lane.
 */
export const IMAGE_CALL_DEADLINE_MS = 180_000;
/** One image per response; the state records which tool call owns the slot. */
export const SLACK_IMAGE_CALL_BUDGET_NAME = 'slackImageCallBudget';

const DEFAULT_IMAGE_BASENAME = 'image';
/** Detail codes are diagnosis tokens, not messages. */
const MAX_IMAGE_DETAIL_CHARS = 64;
const IMAGE_HANDLE = new RegExp(`^${THREAD_IMAGE_HANDLE_PREFIX}[1-9][0-9]{0,2}$`);
// The provider's edit endpoint takes these; a thread GIF is an image the
// inventory can address but not an input this adapter may send.
const PROVIDER_INPUT_MIME_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp']);
const FORMAT_EXTENSIONS: Record<ImageOutputFormat, string> = {
  png: 'png',
  jpeg: 'jpg',
  webp: 'webp',
};

/** The transport facts the format policy needs; resolved lazily. */
export interface ImageToolTransport {
  maxBytes: number;
}

/**
 * The response's one image slot. `release` is present when the Root Agent's
 * budget hook supplied it, so a call that fails before the provider hands the
 * slot back instead of burning the response's only image call.
 */
export interface ImageCallReservation {
  (toolCallId: string): boolean;
  release?(toolCallId: string): void;
}

export type ImageClientResolution =
  | { ok: true; client: OpenAiImagesClient }
  | { ok: false; reason: 'misconfigured' };

export interface ImageArtifactToolOptions {
  /** From the frozen plan's capability: image input fields exist only here. */
  acceptsImageInput: boolean;
  /** Per-turn handles for images already in this conversation. */
  inventory: ThreadImageInventory;
  /** Keyed by tool call id so a durable replay keeps the slot it already took. */
  reserveImageCall: ImageCallReservation;
  /** The installation's upload cap, known only after transport resolution. */
  resolveTransport(): Promise<ImageToolTransport>;
  /** Resolves the model id and provider credential at call time. */
  resolveClient(): Promise<ImageClientResolution>;
  /** Bounded reads through the existing attachment path. */
  createImageReader(limits: {
    perFileLimitBytes: number;
    totalLimitBytes: number;
    signal?: AbortSignal;
  }): Promise<ThreadImageReader>;
  stageArtifact(input: SlackArtifactStageInput): Promise<SlackArtifactStageOutcome>;
}

/**
 * Which half of the pipeline produced an `unavailable` result. The two look
 * identical from Slack, so the Agent could not previously tell "the provider
 * never returned an image" from "the image exists but would not attach"; the
 * source and detail make the reply say which, without naming internals.
 */
export type ImageUnavailableSource = 'provider' | 'staging';

/**
 * A bounded diagnosis token for an `unavailable` result. With `source:
 * 'staging'` it is a `SlackArtifactStagingDetail`, or `bytes_unavailable` when
 * a replay no longer holds the generated bytes. With `source: 'provider'` it is
 * the images client's own code — `redirect_rejected`, `response_too_large`,
 * `invalid_response`, `rate_limited`, `network_error`, `http_<status>`, or an
 * identifier-shaped code the provider named — and `unknown` when it named none.
 */
export type ImageUnavailableDetail = string;

/** One attached variation, in the order the provider returned them. */
export interface ImageArtifactFile {
  filename: string;
  byteLength: number;
}

/** Why one generated variation could not be attached while the rest still may be. */
export type ImageUnattachedFailure =
  | Extract<SlackArtifactStageOutcome, { attached: false; reason: 'missing-scope' | 'too-large' }>
  | { attached: false; reason: 'unavailable'; source: ImageUnavailableSource; detail: ImageUnavailableDetail };

/** A variation that was generated but could not be attached, named by its file. */
export type ImageArtifactUnattachedFile = { filename: string } & ImageUnattachedFailure;

/**
 * Every outcome is a returned value; only the delivery gate throws. An
 * attached result names its first file at the top level, as it always has,
 * and lists every attached variation under `files`; variations that failed
 * to attach are listed under `unattached` so the reply can say which.
 */
export type ImageArtifactResult =
  | {
      attached: true;
      filename: string;
      byteLength: number;
      appliedModel: string;
      appliedSize: string;
      appliedFormat: ImageOutputFormat;
      usage?: ImageCallUsage;
      files: ImageArtifactFile[];
      unattached?: ImageArtifactUnattachedFile[];
    }
  | Extract<SlackArtifactStageOutcome, { attached: false; reason: 'missing-scope' | 'too-large' }>
  | {
      attached: false;
      reason: 'unavailable';
      source: ImageUnavailableSource;
      detail: ImageUnavailableDetail;
    }
  | { attached: false; reason: 'timeout' }
  | { attached: false; reason: 'rejected' }
  | { attached: false; reason: 'misconfigured' }
  | { attached: false; reason: 'limit' }
  | {
      attached: false;
      reason: 'input-unavailable';
      detail: ThreadImageUnavailableDetail;
      handle: string;
    };

/** Recorded by each staging step: the mapped outcome and never bytes. */
type ImageStagingStep =
  | { ok: true; byteLength: number }
  | { ok: false; failure: Extract<ImageArtifactResult, { attached: false }> };

/** One generated variation as the generate step records it: size only, never bytes. */
type ImageGeneratedOutput = { byteLength: number; tooLarge?: true };

/**
 * Recorded by `step.do('generate')`: metadata and never bytes. `outputs`
 * arrived with variations; a record written before it carries the single
 * image's `byteLength` at the top level and replays as one output.
 */
type ImageGenerationStep =
  | {
      ok: true;
      byteLength: number;
      outputs?: ImageGeneratedOutput[];
      /** The upload cap the outputs were judged against; recorded so a replay reports the same limit. */
      maxBytes?: number;
      appliedModel: string;
      appliedSize: string;
      appliedFormat: ImageOutputFormat;
      usage?: ImageCallUsage;
    }
  | { ok: false; failure: Extract<ImageArtifactResult, { attached: false }> };

const PROMPT_FIELD = v.pipe(
  v.string(),
  v.trim(),
  v.minLength(1),
  v.maxLength(MAX_IMAGE_PROMPT_CHARS),
);
const FILENAME_FIELD = v.optional(
  v.pipe(v.string(), v.trim(), v.minLength(1), v.maxLength(MAX_ARTIFACT_FILENAME_CHARS)),
);
const COUNT_FIELD = v.optional(
  v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(MAX_IMAGE_TOOL_OUTPUTS)),
);

const IMAGE_GENERATE_INPUT = v.object({
  prompt: PROMPT_FIELD,
  filename: FILENAME_FIELD,
  count: COUNT_FIELD,
});
const IMAGE_EDIT_INPUT = v.object({
  prompt: PROMPT_FIELD,
  filename: FILENAME_FIELD,
  count: COUNT_FIELD,
  inputs: v.optional(
    v.pipe(
      v.array(v.pipe(v.string(), v.regex(IMAGE_HANDLE))),
      v.maxLength(MAX_IMAGE_TOOL_INPUTS),
    ),
  ),
});

type ImageToolData = v.InferOutput<typeof IMAGE_EDIT_INPUT>;

function imageToolDescription(acceptsImageInput: boolean): string {
  return [
    'Generate an image and attach it to your final reply in the bound Slack destination.',
    'Write the whole prompt yourself from the conversation; the workspace owns the model, so pass no model, size, or quality.',
    acceptsImageInput
      ? `To edit or combine images already in this conversation, list their img:N handles in inputs (at most ${MAX_IMAGE_TOOL_INPUTS}); with no inputs the model generates from the prompt alone.`
      : 'This model generates from the prompt alone and cannot take an existing image as input.',
    `One image call per reply. To offer variations of the same prompt, pass count (1-${MAX_IMAGE_TOOL_OUTPUTS}) in that one call; each variation attaches as its own file, and the result lists them under files.`,
    'The result reports the model and settings the provider applied.',
    'If the result reports attached: false, explain the returned reason and never say an image was attached or edited. A result may attach some variations and list the rest under unattached; say how many attached and why the others did not.',
  ].join(' ');
}

/**
 * The one image tool. The host owns the destination, the model, and the
 * output format; the model chooses only the prompt, optional thread image
 * handles, a filename, and how many variations to render. Generation runs in
 * one durable step and each variation stages in its own, so a replayed tool
 * call neither pays for a second render nor stages any file twice.
 */
export function createImageArtifactTool(options: ImageArtifactToolOptions) {
  return defineTool({
    name: GENERATE_IMAGE_TOOL_NAME,
    description: imageToolDescription(options.acceptsImageInput),
    input: (options.acceptsImageInput
      ? IMAGE_EDIT_INPUT
      : IMAGE_GENERATE_INPUT) as typeof IMAGE_EDIT_INPUT,
    durable: true,
    async run({ data, toolCallId, step, signal }) {
      assertArtifactDeliveryAllowed();
      if (!options.reserveImageCall(toolCallId)) {
        return imageToolOutput({ attached: false, reason: 'limit' });
      }
      // Held only for this execution: a replay resumes with the recorded
      // metadata and no bytes, and reports honestly instead of regenerating.
      let generatedImages: Uint8Array[] | undefined;
      const generated = await step.do('generate', async (): Promise<ImageGenerationStep> => {
        const transport = await options.resolveTransport();
        const format = imageFormatPolicyForTransport(transport.maxBytes, data.prompt);
        const inputs = await resolveImageInputs(options, data, signal);
        if ('failure' in inputs) return { ok: false, failure: inputs.failure };
        const resolved = await options.resolveClient();
        if (!resolved.ok) return { ok: false, failure: { attached: false, reason: 'misconfigured' } };
        const request = {
          prompt: data.prompt,
          format,
          deadlineMs: IMAGE_CALL_DEADLINE_MS,
          count: data.count ?? 1,
          ...(signal ? { signal } : {}),
        };
        const result = inputs.images.length > 0
          ? await resolved.client.edit({ ...request, inputs: inputs.images })
          : await resolved.client.generate(request);
        if (!result.ok) {
          return { ok: false, failure: providerFailure(result) };
        }
        // An oversized variation is dropped on its own; the call fails only
        // when nothing it rendered can be attached.
        const outputs: ImageGeneratedOutput[] = result.images.map((image) => (
          image.byteLength > transport.maxBytes
            ? { byteLength: image.byteLength, tooLarge: true }
            : { byteLength: image.byteLength }
        ));
        if (outputs.every((output) => output.tooLarge)) {
          return {
            ok: false,
            failure: { attached: false, reason: 'too-large', maxBytes: transport.maxBytes },
          };
        }
        generatedImages = result.images;
        return {
          ok: true,
          byteLength: outputs[0]!.byteLength,
          outputs,
          maxBytes: transport.maxBytes,
          appliedModel: result.appliedModel,
          appliedSize: result.appliedSize,
          appliedFormat: result.appliedFormat,
          ...(result.usage ? { usage: result.usage } : {}),
        };
      });
      if (!generated.ok) {
        // Nothing was spent yet, so a corrective retry in this response should
        // not meet `limit`. Provider-side outcomes keep the slot reserved.
        if (isPreProviderFailure(generated.failure)) {
          options.reserveImageCall.release?.(toolCallId);
        }
        return imageToolOutput(generated.failure);
      }

      const outputs = generated.outputs ?? [{ byteLength: generated.byteLength }];
      const filenames = imageFilenames(data.filename, generated.appliedFormat, outputs.length);
      const files: ImageArtifactFile[] = [];
      const unattached: ImageArtifactUnattachedFile[] = [];
      let firstFailure: Extract<ImageArtifactResult, { attached: false }> | undefined;
      for (const [index, output] of outputs.entries()) {
        const filename = filenames[index]!;
        if (output.tooLarge) {
          const maxBytes = generated.maxBytes ?? (await options.resolveTransport()).maxBytes;
          const failure = { attached: false, reason: 'too-large', maxBytes } as const;
          unattached.push({ filename, ...failure });
          firstFailure ??= failure;
          continue;
        }
        // The mapped outcome is what the step records, so a replay reports the
        // same source and detail the first execution actually met. The first
        // variation keeps the step name a single-image record already used.
        const staged = await step.do(stagingStepName(index), async (): Promise<ImageStagingStep> => {
          // Reached only when this execution generated the bytes. A replay that
          // lost them never stages a second file for the same tool call.
          const bytes = generatedImages?.[index];
          if (!bytes) {
            return {
              ok: false,
              failure: {
                attached: false, reason: 'unavailable', source: 'staging', detail: 'bytes_unavailable',
              },
            };
          }
          const outcome = await options.stageArtifact({ bytes, filename, kind: 'image' });
          return outcome.attached
            ? { ok: true, byteLength: outcome.byteLength }
            : { ok: false, failure: stagingFailure(outcome) };
        });
        if (staged.ok) {
          files.push({ filename, byteLength: output.byteLength });
        } else {
          firstFailure ??= staged.failure;
          if (isUnattachedFileFailure(staged.failure)) unattached.push({ filename, ...staged.failure });
        }
      }
      if (files.length === 0) return imageToolOutput(firstFailure!);
      return imageToolOutput({
        attached: true,
        filename: files[0]!.filename,
        byteLength: files[0]!.byteLength,
        appliedModel: generated.appliedModel,
        appliedSize: generated.appliedSize,
        appliedFormat: generated.appliedFormat,
        ...(generated.usage ? { usage: generated.usage } : {}),
        files,
        ...(unattached.length > 0 ? { unattached } : {}),
      });
    },
  });
}

/** The first variation keeps the `stage` name earlier records used; the rest are numbered. */
function stagingStepName(index: number): string {
  return index === 0 ? 'stage' : `stage:${index + 1}`;
}

/** Staging outcomes that describe one file rather than the whole call. */
function isUnattachedFileFailure(
  failure: Extract<ImageArtifactResult, { attached: false }>,
): failure is ImageUnattachedFailure {
  return failure.reason === 'missing-scope' || failure.reason === 'too-large' ||
    failure.reason === 'unavailable';
}

/**
 * The result the model sees. Every field is host-shaped — the client already
 * projected the provider's usage onto known numeric fields — so the JSON
 * contract is asserted here rather than re-validated field by field.
 */
function imageToolOutput(result: ImageArtifactResult): { output: JsonValue } {
  return { output: result as unknown as JsonValue };
}

async function resolveImageInputs(
  options: ImageArtifactToolOptions,
  data: ImageToolData,
  signal: AbortSignal | undefined,
): Promise<{ images: ImageInput[] } | { failure: Extract<ImageArtifactResult, { attached: false }> }> {
  const handles = options.acceptsImageInput ? data.inputs ?? [] : [];
  if (handles.length === 0) return { images: [] };
  const reader = await options.createImageReader({
    // The transport cap bounds the image this call sends back to Slack, not
    // the inputs it reads: the same gateway reads attachments to the Slack cap.
    perFileLimitBytes: DEFAULT_THREAD_IMAGE_FILE_LIMIT_BYTES,
    totalLimitBytes: MAX_ARTIFACT_BYTES,
    ...(signal ? { signal } : {}),
  });
  const images: ImageInput[] = [];
  for (const handle of handles) {
    const resolution = options.inventory.resolveHandle(handle);
    if (!resolution.ok) return { failure: inputUnavailable(handle, resolution.detail) };
    const read = await reader.read(resolution.record);
    if (!read.ok) return { failure: inputUnavailable(handle, read.detail) };
    if (!PROVIDER_INPUT_MIME_TYPES.has(read.mimeType)) {
      return { failure: inputUnavailable(handle, 'unsupported_type') };
    }
    images.push({ bytes: read.bytes, mimeType: read.mimeType });
  }
  return { images };
}

function inputUnavailable(
  handle: string,
  detail: ThreadImageUnavailableDetail,
): Extract<ImageArtifactResult, { reason: 'input-unavailable' }> {
  return { attached: false, reason: 'input-unavailable', detail, handle };
}

/**
 * Direct installations take the provider default as PNG. A shared gateway
 * caps uploads far lower, so it asks for a compressed format: WebP when the
 * request wants transparency, JPEG otherwise.
 */
export function imageFormatPolicyForTransport(maxBytes: number, prompt: string): ImageFormatPolicy {
  if (maxBytes >= MAX_ARTIFACT_BYTES) return { format: 'png' };
  return {
    format: wantsTransparentBackground(prompt) ? 'webp' : 'jpeg',
    compression: compressionForCap(maxBytes),
  };
}

/**
 * Only the container format is chosen here: `background` stays unset so the
 * provider's own default decides, and a prompt that merely mentions
 * transparency cannot force an alpha channel onto an opaque image.
 */
function wantsTransparentBackground(prompt: string): boolean {
  return /\btransparen(?:t|cy)\b/i.test(prompt);
}

function compressionForCap(maxBytes: number): number {
  if (maxBytes >= 4 * 1024 * 1024) return 90;
  if (maxBytes >= 1024 * 1024) return 80;
  return 60;
}

/**
 * Client failures the tool reports. Nothing carries prompt text; an
 * `unavailable` result names the provider as its source and carries the
 * client's bounded detail code, so an unreachable provider and a file that
 * would not attach stop reading identically to the Agent.
 */
function providerFailure(
  result: Extract<ImageCallResult, { ok: false }>,
): Extract<ImageArtifactResult, { attached: false }> {
  const reason = providerFailureReason(result.reason);
  return reason === 'unavailable'
    ? {
        attached: false,
        reason: 'unavailable',
        source: 'provider',
        detail: providerDetail(result.detail),
      }
    : { attached: false, reason };
}

function providerFailureReason(
  reason: ImageCallFailureReason,
): 'rejected' | 'misconfigured' | 'timeout' | 'unavailable' {
  if (reason === 'rejected' || reason === 'misconfigured' || reason === 'timeout') return reason;
  // A transport failure and a request this build should never have sent are
  // both "no image, try later"; neither is the content's fault.
  return 'unavailable';
}

/** The client already bounds its codes; an empty one still needs a name. */
function providerDetail(detail: string): ImageUnavailableDetail {
  const trimmed = detail.trim();
  return trimmed.length > 0 && trimmed.length <= MAX_IMAGE_DETAIL_CHARS ? trimmed : 'unknown';
}

/**
 * A staging outcome as the image tool reports it: `unavailable` gains the
 * staging source and the host-authored category.
 */
function stagingFailure(
  outcome: Extract<SlackArtifactStageOutcome, { attached: false }>,
): Extract<ImageArtifactResult, { attached: false }> {
  if (outcome.reason !== 'unavailable') return outcome;
  return {
    attached: false,
    reason: 'unavailable',
    source: 'staging',
    detail: outcome.detail ?? 'unknown',
  };
}

/** Failures raised before the provider ran: no image was paid for. */
function isPreProviderFailure(
  failure: Extract<ImageArtifactResult, { attached: false }>,
): boolean {
  return failure.reason === 'input-unavailable' || failure.reason === 'misconfigured';
}

/** Keep the Slack-visible filename a safe basename matching the applied format. */
export function imageFilename(
  requested: string | undefined,
  format: ImageOutputFormat,
): string {
  return artifactFilename(requested, DEFAULT_IMAGE_BASENAME, FORMAT_EXTENSIONS[format]);
}

/**
 * One safe filename per variation. A single image keeps the requested name;
 * variations share its basename with a 1-based suffix (`ad-1.jpg`, `ad-2.jpg`)
 * so the files stay distinguishable in Slack and in the next turn's listing.
 */
export function imageFilenames(
  requested: string | undefined,
  format: ImageOutputFormat,
  count: number,
): string[] {
  const single = imageFilename(requested, format);
  if (count <= 1) return [single];
  const extension = `.${FORMAT_EXTENSIONS[format]}`;
  const suffixLength = `-${count}`.length;
  // Trim separators the sanitizer left at the end and leave room for the
  // suffix, so `weird-name-` becomes `weird-name-1` and a basename at the
  // length cap still yields distinct names.
  const base = single
    .slice(0, single.length - extension.length)
    .slice(0, MAX_ARTIFACT_FILENAME_CHARS - suffixLength)
    .replace(/[-.]+$/, '');
  return Array.from({ length: count }, (_, index) => (
    imageFilename(`${base || DEFAULT_IMAGE_BASENAME}-${index + 1}`, format)
  ));
}

interface ImageCallBudgetState {
  schemaVersion: 1;
  /** The tool call that owns this response's one image call. */
  toolCallId: string | null;
}

/**
 * Root-Agent hook: one image call per response. The reservation is
 * keyed by tool call id, so a durable replay of the same call keeps the slot
 * it already took and a second call in the same response is refused.
 */
export function useImageCallBudget(): ImageCallReservation {
  const [, update] = usePersistentState<ImageCallBudgetState>(
    SLACK_IMAGE_CALL_BUDGET_NAME,
    { schemaVersion: 1, toolCallId: null },
  );
  useResponseStart(() => { update({ schemaVersion: 1, toolCallId: null }); });
  const reserve = (toolCallId: string) => {
    let allowed = false;
    update((previous) => {
      const owner = previous?.toolCallId ?? null;
      allowed = owner === null || owner === toolCallId;
      return allowed ? { schemaVersion: 1, toolCallId } : { schemaVersion: 1, toolCallId: owner };
    });
    return allowed;
  };
  return Object.assign(reserve, {
    // Only the owner may hand the slot back, so a losing second call cannot
    // free the reservation the first call is still using.
    release(toolCallId: string) {
      update((previous) => {
        const owner = previous?.toolCallId ?? null;
        return { schemaVersion: 1, toolCallId: owner === toolCallId ? null : owner };
      });
    },
  });
}
