// Generated by scripts/build-agent-avatar-pool.mjs. Do not edit by hand.
export const DEFAULT_AGENT_AVATAR_FILES = [
  "01-sage.png",
  "02-coral.png",
  "03-lilac.png",
  "04-mineral-blue.png",
  "05-dusty-rose.png",
  "06-deep-moss.png",
  "07-periwinkle.png",
  "08-seafoam.png",
  "09-warm-oat.png",
  "10-midnight-indigo.png",
  "11-apricot.png",
  "12-muted-berry.png"
] as const;
