// Generated by scripts/build-chickpea-product-mark.mjs. Do not edit by hand.
export const CHICKPEA_MARK_URL = "/chickpea-mark-128.png?v=bf7cc48a8553";

export const CHICKPEA_FAVICON_URL = "/chickpea-favicon-32.png?v=201aece87c3b";

export const CHICKPEA_WORDMARK_URL = "/chickpea-wordmark-512.png?v=f29e8f737ea7";
